### ISSUE TITLE
Use basic selectors

### ISSUE THREAD

**Issue by warren231** [warren231/sp24-cse110-lab3#17]
**Describe the task.**
Include the selectors below

**Subtasks, if any**
List any subtasks here.
- [ ] Class Selector (.class)
- [ ] ID Selector (#id)
- [ ] Universal Selector (*)
- [ ] Element Selector (element) 
- [ ] Attribute Selector (e.g. [attribute=foo])     
- [ ] Pseudo-class Selector (e.g. p:hover)
- [ ] Selector List (element, element) /* select multiple elements */
