### ISSUE TITLE
Include combinator selectors

### ISSUE THREAD

**Issue by warren231** [warren231/sp24-cse110-lab3#18]
**Describe the task.**
Include combinator selectors.

**Subtasks, if any**
List any subtasks here.
- [ ] Descendant Combinator (element element)
- [ ] Child Combinator (element > element)
- [ ] General sibling combinator (element ~ element)
- [ ] Adjacent sibling combinator (element + element)
- [ ] Combining Two Selectors (element.class)
